# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install Playwright CLI
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        export PATH="$PATH:$HOME/.dotnet/tools"
    - name: Install Playwright
      run: |
        dotnet add package Microsoft.Playwright --version 1.49.0
        dotnet restore  # Ensure all dependencies are restored
    - name: Build
      run: dotnet build
    - name: Install Playwright browsers
      run: dotnet playwright install
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
