name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Install Playwright
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install

    - name: Run tests and check .trx file
      id: test
      run: |
        OUTPUT=$(dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx")
        echo "$OUTPUT"

        # Extract total tests and passed tests
        TOTAL_TESTS=$(echo "$OUTPUT" | grep -oP 'Total tests: \K\d+')
        PASSED_TESTS=$(echo "$OUTPUT" | grep -oP 'Passed: \K\d+')

        # Format the result
        TEST_RESULT="${TOTAL_TESTS}/${PASSED_TESTS}"

        echo "TEST_RESULT=$TEST_RESULT"
        echo "TEST_RESULT=$TEST_RESULT" >> $GITHUB_ENV
    
    - name: Update Gist with Test Results
      if: always()
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 47477479896ebb9ad4156c5f274fb438
        filename: tests.json
        label: tests
        message: ${{ env.TEST_RESULT }} 
        color: success

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: "**/TestResults/*.trx"
        reporter: dotnet-trx
