name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Install Playwright
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install

    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils

    - name: Test and Extract Count
      id: test
      run: |
        OUTPUT=$(dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx")
        echo "$OUTPUT"
        # Parse the .trx file and extract the number of tests passed using xmllint
        TEST_COUNT=$(xmllint --xpath "string(//test-run/@total)" test-results.trx)
        echo "TEST_COUNT=$TEST_COUNT" >> $GITHUB_ENV
    
    - name: Update Gist with Test Results
      if: always()
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 47477479896ebb9ad4156c5f274fb438
        filename: tests.json
        label: tests
        message: ${{ env.TEST_COUNT }} passed
        color: success

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: "**/TestResults/*.trx"
        reporter: dotnet-trx
